#!/bin/bash
exec 2>&1
echo "Starting Apache Tomcat"

export JAVA_HOME={{pkgPathFor "core/jre8"}}
export TOMCAT_HOME={{pkg.svc_var_path}}/tc

{{#if bind.database ~}}
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{bind.database.first.sys.ip}} -DMONGODB_SERVICE_PORT={{bind.database.first.cfg.port}}"
{{else ~}}
echo "I've got no database bound, yo."
{{/if ~}}

echo "\$CATALINA_OPTS=$CATALINA_OPTS"

cp "{{pkg.path}}/{{pkg.name}}.war" "$TOMCAT_HOME/webapps/"

exec ${TOMCAT_HOME}/bin/catalina.sh run

